### ISSUE TITLE
Tomorrow Theme

### ISSUE THREAD

**Issue by Solistor** [Zyst/discord-4chan-theme#3]
'Ello! I have no fuckin clue about this github thing, so I'm not sure if there's some sort of special protocol for this, but I edited in a Tomorrow theme addition that automatically switches when you use Dark Mode on Discord.

It's a little hackneyed but it works, just change the filetype to .css (though you probably already knew that)
[4chan.theme.txt](https://github.com/Zyst/discord-4chan-theme/files/491251/4chan.theme.txt)

**Comment by Zyst** [comment]
wwwww
